"""v1_mvp_inquiry

Revision ID: 24bd995dc7ac
Revises: 
Create Date: 2026-06-07 18:40:52.840182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '24bd995dc7ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_code', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('customer_short_name', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('customer_category', sa.Text(), nullable=True),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('responsible_sales', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=False),
    sa.Column('group_leader', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('success_rows', sa.Integer(), nullable=True),
    sa.Column('failed_rows', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_no', sa.Text(), nullable=False),
    sa.Column('customer_code', sa.Text(), nullable=True),
    sa.Column('customer_order_no', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('customer_short_name', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('customer_category', sa.Text(), nullable=True),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('responsible_sales', sa.Text(), nullable=True),
    sa.Column('assisting_sales', sa.Text(), nullable=True),
    sa.Column('product_category', sa.Text(), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('series_name', sa.Text(), nullable=True),
    sa.Column('season', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('inquiry_date', sa.Date(), nullable=True),
    sa.Column('quote_status', sa.Text(), nullable=True),
    sa.Column('order_status', sa.Text(), nullable=True),
    sa.Column('final_quote', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('factory_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('gross_profit_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('order_unit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('trade_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('inquiry_year', sa.SmallInteger(), nullable=True),
    sa.Column('inquiry_month', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_customer_code'), 'inquiries', ['customer_code'], unique=False)
    op.create_index(op.f('ix_inquiries_group_name'), 'inquiries', ['group_name'], unique=False)
    op.create_index(op.f('ix_inquiries_import_batch_id'), 'inquiries', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_inquiries_inquiry_no'), 'inquiries', ['inquiry_no'], unique=True)
    op.create_index(op.f('ix_inquiries_inquiry_year'), 'inquiries', ['inquiry_year'], unique=False)
    op.create_index(op.f('ix_inquiries_order_status'), 'inquiries', ['order_status'], unique=False)
    op.create_index(op.f('ix_inquiries_responsible_sales'), 'inquiries', ['responsible_sales'], unique=False)
    op.create_index(op.f('ix_inquiries_season'), 'inquiries', ['season'], unique=False)
    op.create_index(op.f('ix_inquiries_series_name'), 'inquiries', ['series_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('import_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('inquiry_no', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('raw_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_rows_batch_id'), 'import_rows', ['batch_id'], unique=False)
    op.create_table('inquiry_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('inquiry_no', sa.Text(), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('product_category', sa.Text(), nullable=True),
    sa.Column('series_name', sa.Text(), nullable=True),
    sa.Column('fabric_quality', sa.Text(), nullable=True),
    sa.Column('color_print', sa.Text(), nullable=True),
    sa.Column('size_range', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('quote_status', sa.Text(), nullable=True),
    sa.Column('order_status', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiry_items_inquiry_id'), 'inquiry_items', ['inquiry_id'], unique=False)
    op.create_index(op.f('ix_inquiry_items_inquiry_no'), 'inquiry_items', ['inquiry_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inquiry_items_inquiry_no'), table_name='inquiry_items')
    op.drop_index(op.f('ix_inquiry_items_inquiry_id'), table_name='inquiry_items')
    op.drop_table('inquiry_items')
    op.drop_index(op.f('ix_import_rows_batch_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_table('users')
    op.drop_index(op.f('ix_inquiries_series_name'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_season'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_responsible_sales'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_order_status'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_inquiry_year'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_inquiry_no'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_import_batch_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_group_name'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_customer_code'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_table('import_batches')
    op.drop_table('groups')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
